# Generated by Django 5.0.1 on 2024-01-05 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apology', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('apology', 'user', 'user_id'),
    ]
