# Generated by Django 5.0.1 on 2024-01-05 19:34

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('apology', '0003_auto_20240105_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='apology',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
