# Generated by Django 5.0.1 on 2024-01-06 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apology', '0004_auto_20240105_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_created_at', models.DateTimeField()),
                ('ai_id', models.TextField(unique=True)),
                ('completion_tokens', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('messages', models.JSONField()),
                ('model', models.TextField()),
                ('prompt_tokens', models.IntegerField()),
                ('apology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apology.apology')),
            ],
        ),
    ]
